name: br_educacao
version: "1.0.0"
config-version: 2

profile: inep_postgres

model-paths: ["models"]
seed-paths:  ["seeds"]

seeds:
  br_educacao:
    +schema: bronze

models:
  br_educacao:
    
    # Camada RAW
    raw:
      +schema: raw
      +materialized: view

    # Camada SILVER
    silver:
      +schema: silver
      +materialized: table

    # Camada GOLD
    gold:
      +schema: gold
      +materialized: table
