name: br_educacao
version: "1.0.0"
config-version: 2

profile: inep_postgres

model-paths: ["models"]
seed-paths:  ["seeds"]

seeds:
  br_educacao:
    +schema: bronze

models:
  br_educacao:
    +materialized: view

    raw:
      +schema: bronze
      +materialized: view

    silver:
      +schema: silver
      +materialized: table

    gold:
      +schema: gold
      +materialized: table
