version: "3.8"

services:
  # ----------------------------------------------
  # Serviço que executa a extração + dbt
  pipeline:
    image: python:3.11-slim
    container_name: inep-pipeline
    env_file:
      - ./.env
    environment:
      - DBT_PROFILES_DIR=/opt/app/dbt/profiles
    volumes:
      - ./:/opt/app
    working_dir: /opt/app
    command: >
      bash -c "
      pip install --no-cache-dir -r requirements.txt &&
      python inep/run_pipeline.py
      "

  # ----------------------------------------------
  # Serviço CLI dbt (opcional, para rodar comandos à parte)
  dbt-cli:
    image: ghcr.io/dbt-labs/dbt-postgres:1.7.14
    container_name: dbt-cli
    env_file:
      - ./.env
    environment:
      - DBT_PROFILES_DIR=/opt/dbt/profiles
      - POSTGRES_HOST=${POSTGRES_HOST}
    volumes:
      - ./dbt:/opt/dbt
      - ./.env:/opt/dbt/.env:ro
    working_dir: /opt/dbt

  # ----------------------------------------------
  # Serviço do PostgreSQL 9.3
  postgres:
    image: postgres:9.3
    container_name: inep-postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  default:
    name: inep-net

volumes:
  postgres_data:
